(ns profile-test (:require [cljs.reader :as r] ["fs" :as fs]))
(def p (r/read-string (.readFileSync fs ".itonami/profile.edn" "utf8")))
(def markets (r/read-string (.readFileSync fs "data/markets.edn" "utf8")))
(assert (= "cloud.itonami.app.repo-profile.v1" (:profile/schema p)))
(assert (= "x402-qr-growth" (:profile/id p)))
(assert (< (count (:bot/brief p)) 2000))
(assert (every? #{:profile/schema :profile/id :bot/name :bot/brief :bot/context-refs :bot/tools-requested} (keys p)))
(assert (every? #(= :hypothesis (:status %)) (:markets markets)))
(assert (every? #(.existsSync fs %) (:bot/context-refs p)))
(println "Profile contract PASS")
